/-
Copyright (c) 2026 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Ristretto.Representation
import Curve25519Dalek.Specs.Backend.Serial.U64.Field.FieldElement51.FromBytes
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.ElligatorRistrettoFlavor
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.Add

/-! # Spec Theorem for `RistrettoPoint::from_uniform_bytes`

Specification and proof for `RistrettoPoint::from_uniform_bytes`.

This function constructs a uniformly sampled `RistrettoPoint` from 64 bytes of uniform random data
by applying the Ristretto-flavored Elligator map to two field elements generated by two 32-byte halfs
and adding the resulting two Ristretto points via elliptic curve addition.

**Source**: curve25519-dalek/src/ristretto.rs
-/

open Aeneas Aeneas.Std Result core.ops.range Aeneas.Std.WP

-- To be upstreamed to Aeneas.
-- Progress spec for immutable range-based slice indexing.
-- The mutable counterpart `SliceIndexRangeUsizeSlice.index_mut.progress_spec` exists in
-- aeneas (Slice.lean) but this immutable version is missing.
@[progress]
theorem core.slice.index.SliceIndexRangeUsizeSlice.index.progress_spec {α : Type}
    (r : core.ops.range.Range Usize) (s : Slice α) (h0 : r.start ≤ r.end) (h1 : r.end ≤ s.length) :
    core.slice.index.SliceIndexRangeUsizeSlice.index r s ⦃ (s1 : Slice α) =>
      s1.val = s.val.slice r.start r.end ∧
      s1.length = r.end - r.start ⦄ := by
  simp only [core.slice.index.SliceIndexRangeUsizeSlice.index, UScalar.le_equiv, Slice.length]
  split
  · simp only [spec_ok, true_and]
    simp_lists
    omega
  · simp only [spec_fail]
    scalar_tac

namespace curve25519_dalek.ristretto.RistrettoPoint

/-
natural language description:

The Ristretto group is a prime-order group constructed as a quotient of the Edwards curve.
The `from_uniform_bytes` function implements a map from 64 bytes to Ristretto group elements
that ensures a uniform distribution: if the input bytes are uniformly random, the output
Ristretto point is uniformly distributed over the Ristretto group.

The mapping is achieved by:

- Splitting the 64-byte input into two 32-byte halves
- Taking the low 255 bits of each half modulo p and converting to a field element (via `from_bytes`)
- Applying the Ristretto-flavored Elligator map to each field element to transform it into a Ristretto point
- Adding the two resulting Ristretto points via elliptic curve addition

natural language specs:

- The function always succeeds (no panic) for arbitrary 64-byte inputs
- The output is a mathematically valid Ristretto point (i.e., an even Edwards point that lies on the curve)
-/

/-
def split64to32 (input : Array U8 64#usize) : Result (Array U8 32#usize × Array U8 32#usize) :=
  let a1 := input.subslice (Range.mk 0#usize 32#usize)
  let a2 := input.subslice (Range.mk 32#usize 64#usize)
  match a1, a2 with
  | ok s1, ok s2 => ok (Array.from_slice (Array.repeat 32#usize 0#u8) s1,
                        Array.from_slice (Array.repeat 32#usize 0#u8) s2)
  | _, _ => fail Error.panic
-/

/-- **Spec and proof concerning `ristretto.RistrettoPoint.from_uniform_bytes`**:
- The function always succeeds (no panic) for arbitrary 64-byte inputs
- The output is a mathematically valid Ristretto point (i.e., an even Edwards point that lies on the curve)
-/
@[progress]
theorem from_uniform_bytes_spec (bytes : Array U8 64#usize) :
    from_uniform_bytes bytes ⦃ (rist : RistrettoPoint) =>
      rist.IsValid ⦄ := by
  unfold from_uniform_bytes
  unfold Insts.CoreOpsArithAddRistrettoPointRistrettoPoint.add
  progress*
  · simp_all [Array.to_slice_mut]
  · unfold backend.serial.u64.field.FieldElement51.IsValid
    grind
  · simp_all [Array.to_slice_mut]
  · unfold backend.serial.u64.field.FieldElement51.IsValid
    grind

end curve25519_dalek.ristretto.RistrettoPoint
