/-
Copyright (c) 2026 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Ristretto.Representation
import Curve25519Dalek.Specs.Backend.Serial.U64.Field.FieldElement51.FromBytes
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.ElligatorRistrettoFlavor
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.Add

/-! # Spec Theorem for `RistrettoPoint::from_uniform_bytes`

Specification and proof for `RistrettoPoint::from_uniform_bytes`.

This function constructs a uniformly sampled `RistrettoPoint` from 64 bytes of uniform random data
by applying the Ristretto-flavored Elligator map to two field elements generated by two 32-byte
halfs and adding the resulting two Ristretto points via elliptic curve addition.

**Source**: curve25519-dalek/src/ristretto.rs
-/

open Aeneas Aeneas.Std Result core.ops.range Aeneas.Std.WP

namespace curve25519_dalek.ristretto.RistrettoPoint

/-
Natural language description:

The Ristretto group is a prime-order group constructed as a quotient of the Edwards curve.
The `from_uniform_bytes` function implements a map from 64 bytes to Ristretto group elements
that ensures a uniform distribution: if the input bytes are uniformly random, the output
Ristretto point is uniformly distributed over the Ristretto group.

The mapping is achieved by:

- Splitting the 64-byte input into two 32-byte halves
- Taking the low 255 bits of each half modulo p and converting to a field element (via `from_bytes`)
- Applying the Ristretto-flavored Elligator map to each field element to transform it into a Ristretto point
- Adding the two resulting Ristretto points via elliptic curve addition

Natural language specs:

- The function always succeeds (no panic) for arbitrary 64-byte inputs
- The output is a mathematically valid Ristretto point (i.e., an even Edwards point that lies on the curve)
-/

/-- **Spec and proof concerning `ristretto.RistrettoPoint.from_uniform_bytes`**:
- The function always succeeds (no panic) for arbitrary 64-byte inputs
- The output is a mathematically valid Ristretto point (i.e., an even Edwards point that lies on the curve)
-/
@[progress]
theorem from_uniform_bytes_spec (bytes : Array U8 64#usize) :
    from_uniform_bytes bytes ⦃ (rist : RistrettoPoint) =>
      rist.IsValid ⦄ := by
  unfold from_uniform_bytes
  unfold Insts.CoreOpsArithAddRistrettoPointRistrettoPoint.add
  progress*
  · simp_all [Array.to_slice_mut]
  · unfold backend.serial.u64.field.FieldElement51.IsValid
    grind
  · simp_all [Array.to_slice_mut]
  · unfold backend.serial.u64.field.FieldElement51.IsValid
    grind

end curve25519_dalek.ristretto.RistrettoPoint
