/-
Copyright (c) 2025 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander, Alessandro D'Angelo
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Basic
import Curve25519Dalek.Aux

-- The long `simp only` blocks generated by `step*` postcondition resolution
-- here contain a handful of arguments not strictly required; the linter is
-- disabled to keep these block ergonomically aligned with `step*`.
set_option linter.unusedSimpArgs false

/-! # Spec Theorem for `Scalar52::from_bytes`

Specification and proof for `Scalar52::from_bytes`.

This function constructs an unpacked scalar from a byte array by:
1. Packing 32 bytes into 4 little-endian U64 words (loop)
2. Extracting 5 limbs via shift/OR/mask (bit-slicing)

**Source**: curve25519-dalek/src/backend/serial/u64/scalar.rs (lines 66-93)

## Proof structure

1. `from_bytes_loop_spec` (`@[step]`):
   Loop packs 32 bytes into 4 U64 words; postcondition uses `word_of_bytes`.
2. `slicing_identity`: Pure Nat-level identity — 5 limbs extracted via
   shift/OR/mask from 4 words reconstruct the same value.
   Decomposed via small `bv_decide` primitives + `linarith` glue.
3. `from_bytes_spec` (`@[step]`): Drives the unfolded body with `step*` /
   `let*`, then closes value and bound obligations via the slicing identity.
-/

open Aeneas Aeneas.Std Result Aeneas.Std.WP
namespace curve25519_dalek.backend.serial.u64.scalar.Scalar52

/-! ## Part 1: Loop spec — byte packing -/

/-- The little-endian value of 8 consecutive bytes starting at position `8*j` in a 32-byte array. -/
abbrev word_of_bytes (bytes : Array U8 32#usize) (j : Nat) : Nat :=
  ∑ k ∈ Finset.range 8, bytes[8 * j + k]!.val * 2 ^ (8 * k)

/-- **Loop spec**: Each iteration packs 8 bytes into one U64 word (little-endian).
After the loop completes, `words[j] = word_of_bytes bytes j` for all `j < 4`. -/
@[step]
theorem from_bytes_loop_spec (bytes : Array U8 32#usize)
    (words : Array U64 4#usize) (i : Usize) (hi : i.val ≤ 4)
    (h_prev : ∀ j, j < i.val → words[j]!.val = word_of_bytes bytes j) :
    from_bytes_loop bytes words i ⦃ words' =>
      ∀ j, j < 4 → words'[j]!.val = word_of_bytes bytes j ⦄ := by
  induction h_rem : (4 - i.val) generalizing i words with
  | zero =>
    unfold from_bytes_loop
    have hi4 : ¬ (i < 4#usize) := by scalar_tac
    simp only [hi4, ↓reduceIte, spec_ok]
    intro j hj; exact h_prev j (by omega)
  | succ n ih =>
    unfold from_bytes_loop
    have hlt : i < 4#usize := by scalar_tac
    simp only [hlt, ↓reduceIte]
    step*
    subst a_post
    intro j hj
    by_cases heq : j = i.val
    · -- j = i: the freshly written word equals the byte sum
      subst heq
      simp only [Array.getElem!_Nat_eq, Array.set_val_eq]
      rw [getElem!_pos _ _ (by simp only [List.length_set, List.Vector.length_val,
        UScalar.ofNatCore_val_eq]; agrind),
          List.getElem_set_self (by simp only [List.length_set, List.Vector.length_val,
            UScalar.ofNatCore_val_eq]; agrind)]
      simp (discharger := omega) only [*, UScalar.val_or, UScalar.cast_val_eq,
        u8_val_mod_u64_numBits, Nat.shiftLeft_eq, u8_mul_pow_mod_u64]
      rw [or_bytes_eq_sum _ _ _ _ _ _ _ _
        (bytes.val[i.val * 8]!).hmax (bytes.val[i.val * 8 + 1]!).hmax
        (bytes.val[i.val * 8 + 2]!).hmax (bytes.val[i.val * 8 + 3]!).hmax
        (bytes.val[i.val * 8 + 4]!).hmax (bytes.val[i.val * 8 + 5]!).hmax
        (bytes.val[i.val * 8 + 6]!).hmax (bytes.val[i.val * 8 + 7]!).hmax]
      simp only [word_of_bytes, Finset.sum_range_succ, Finset.range_zero, Finset.sum_empty,
        zero_add]
      simp only [Array.getElem!_Nat_eq]; ring_nf
    · -- j ≠ i: unchanged entry, use h_prev
      simp only [Array.getElem!_Nat_eq, Array.set_val_eq]
      grind only [= List.getElem!_set_ne, =_ Array.getElem!_Nat_eq]

/-! ## Part 2: Bit-slicing identity

5 limbs from 4 words via the generic `or_split_at` (from `Aux.lean`) plus
`omega` on the resulting linear arithmetic. -/

/-- The bit-slicing identity: the five 52/48-bit limbs extracted from four
64-bit words reconstruct the same natural number. -/
private theorem bit_slicing_of_words (w0 w1 w2 w3 : U64) :
    let l0 := w0.val % 2 ^ 52
    let l1 := ((w0.val / 2 ^ 52) ||| ((w1.val * 2 ^ 12) % U64.size)) % 2 ^ 52
    let l2 := ((w1.val / 2 ^ 40) ||| ((w2.val * 2 ^ 24) % U64.size)) % 2 ^ 52
    let l3 := ((w2.val / 2 ^ 28) ||| ((w3.val * 2 ^ 36) % U64.size)) % 2 ^ 52
    let l4 := (w3.val / 2 ^ 16) % 2 ^ 48
    l0 + l1 * 2 ^ 52 + l2 * 2 ^ 104 + l3 * 2 ^ 156 + l4 * 2 ^ 208
    = w0.val + w1.val * 2 ^ 64 + w2.val * 2 ^ 128 + w3.val * 2 ^ 192 := by
  have hU : U64.size = 2 ^ 64 := by scalar_tac
  have hw0 : w0.val < 2 ^ 64 := hU ▸ w0.hmax
  have hw1 : w1.val < 2 ^ 64 := hU ▸ w1.hmax
  have hw2 : w2.val < 2 ^ 64 := hU ▸ w2.hmax
  have hw3 : w3.val < 2 ^ 64 := hU ▸ w3.hmax
  rw [or_split_at w0 w1 52 (by omega), or_split_at w1 w2 40 (by omega),
      or_split_at w2 w3 28 (by omega)]
  -- Simplify the outer mods: each inner sum fits in 52 / 48 bits
  rw [show (w0.val / 2 ^ 52 + (w1.val % 2 ^ 52) * 2 ^ 12) % 2 ^ 52 =
        w0.val / 2 ^ 52 + w1.val % 2 ^ 40 * 2 ^ 12 from by omega,
      show (w1.val / 2 ^ 40 + (w2.val % 2 ^ 40) * 2 ^ 24) % 2 ^ 52 =
        w1.val / 2 ^ 40 + w2.val % 2 ^ 28 * 2 ^ 24 from by omega,
      show (w2.val / 2 ^ 28 + (w3.val % 2 ^ 28) * 2 ^ 36) % 2 ^ 52 =
        w2.val / 2 ^ 28 + w3.val % 2 ^ 16 * 2 ^ 36 from by omega,
      show w3.val / 2 ^ 16 % 2 ^ 48 = w3.val / 2 ^ 16 from by omega]
  -- Now the equation is linear over div/mod splits
  have := Nat.div_add_mod w0.val (2 ^ 52)
  have := Nat.div_add_mod w1.val (2 ^ 40)
  have := Nat.div_add_mod w2.val (2 ^ 28)
  have := Nat.div_add_mod w3.val (2 ^ 16)
  omega

/-! ## Part 3: Main spec -/

set_option maxHeartbeats 400000 in -- 32 `step*`s plus a long `simp only` glue
/-- **Spec and proof concerning `scalar.Scalar52.from_bytes`**:
- No panic (always returns successfully)
- The result represents the same number as the input byte array
- All limbs are < 2^52 (from masking with `(1 << 52) - 1` and `(1 << 48) - 1`)
-/
@[step]
theorem from_bytes_spec (b : Array U8 32#usize) :
    from_bytes b ⦃ u =>
    Scalar52_as_Nat u = U8x32_as_Nat b ∧
    ∀ i < 5, u[i]!.val < 2 ^ 52 ⦄
    := by
  unfold from_bytes
  let* ⟨ words1, words1_post ⟩ ← from_bytes_loop_spec
  let* ⟨ i, i_post1, i_post2 ⟩ ← U64.ShiftLeft_IScalar_spec
  let* ⟨ mask, mask_post1, mask_post2 ⟩ ← U64.sub_spec
  let* ⟨ i1, i1_post1, i1_post2 ⟩ ← U64.ShiftLeft_IScalar_spec
  let* ⟨ top_mask, top_mask_post1, top_mask_post2 ⟩ ← U64.sub_spec
  let* ⟨ i2, i2_post ⟩ ← Array.index_usize_spec
  -- Eliminate index_mut wrappers
  simp only [Insts.CoreOpsIndexIndexMutUsizeU64.index_mut, Array.index_mut_usize,
             bind_assoc_eq, bind_tc_ok]
  let* ⟨ x, x_post ⟩ ← Array.index_usize_spec
  let* ⟨ i3, i3_post1, i3_post2 ⟩ ← UScalar.and_spec
  let* ⟨ i4, i4_post1, i4_post2 ⟩ ← U64.ShiftRight_IScalar_spec
  let* ⟨ i5, i5_post ⟩ ← Array.index_usize_spec
  let* ⟨ i6, i6_post1, i6_post2 ⟩ ← U64.ShiftLeft_IScalar_spec
  let* ⟨ i7, i7_post1, i7_post2 ⟩ ← UScalar.or_spec
  let* ⟨ x, x_post ⟩ ← Array.index_usize_spec
  let* ⟨ i8, i8_post1, i8_post2 ⟩ ← UScalar.and_spec
  let* ⟨ i9, i9_post1, i9_post2 ⟩ ← U64.ShiftRight_IScalar_spec
  let* ⟨ i10, i10_post ⟩ ← Array.index_usize_spec
  let* ⟨ i11, i11_post1, i11_post2 ⟩ ← U64.ShiftLeft_IScalar_spec
  let* ⟨ i12, i12_post1, i12_post2 ⟩ ← UScalar.or_spec
  let* ⟨ x, x_post ⟩ ← Array.index_usize_spec
  let* ⟨ i13, i13_post1, i13_post2 ⟩ ← UScalar.and_spec
  let* ⟨ i14, i14_post1, i14_post2 ⟩ ← U64.ShiftRight_IScalar_spec
  let* ⟨ i15, i15_post ⟩ ← Array.index_usize_spec
  let* ⟨ i16, i16_post1, i16_post2 ⟩ ← U64.ShiftLeft_IScalar_spec
  let* ⟨ i17, i17_post1, i17_post2 ⟩ ← UScalar.or_spec
  let* ⟨ x, x_post ⟩ ← Array.index_usize_spec
  let* ⟨ i18, i18_post1, i18_post2 ⟩ ← UScalar.and_spec
  let* ⟨ i19, i19_post1, i19_post2 ⟩ ← U64.ShiftRight_IScalar_spec
  let* ⟨ x, x_post ⟩ ← Array.index_usize_spec
  let* ⟨ i20, i20_post1, i20_post2 ⟩ ← UScalar.and_spec
  -- Convert AND → mod via mask values
  have hmask : mask.val = 2 ^ 52 - 1 := by scalar_tac
  have htop : top_mask.val = 2 ^ 48 - 1 := by scalar_tac
  simp only [UScalar.val_and, hmask, land_pow_two_sub_one_eq_mod]
    at i3_post1 i8_post1 i13_post1 i18_post1
  simp only [UScalar.val_and, htop, land_pow_two_sub_one_eq_mod] at i20_post1
  -- Specialize loop post at each word index
  have hw0 := words1_post 0 (by omega)
  have hw1 := words1_post 1 (by omega)
  have hw2 := words1_post 2 (by omega)
  have hw3 := words1_post 3 (by omega)
  -- Per-limb equations: each `hr_k` reads off entry `k` of the freshly-built array.
  -- The simp lists below are the ones produced by `step*`; we keep them verbatim.
  have hr0 :
      ((((((Std.Array.set ZERO 0#usize i3).set 1#usize i8).set 2#usize i13).set 3#usize i18).set
        4#usize i20))[0]!.val = words1[0]!.val % 2 ^ 52 := by
    simp only [↓Array.getElem!_Nat_set_ne, ↓Array.getElem!_Nat_set_eq, UScalar.ofNatCore_val_eq,
      ne_eq, not_false_eq_true, one_ne_zero, OfNat.ofNat_ne_zero, Nat.succ_ne_self,
      Nat.reduceEqDiff, Nat.reduceLT, Nat.lt_add_one, Array.length, List.Vector.length_val,
      Nat.ofNat_pos, and_self, i3_post1, i2_post, ← Array.getElem!_Nat_eq]
  have hr1 :
      ((((((Std.Array.set ZERO 0#usize i3).set 1#usize i8).set 2#usize i13).set 3#usize i18).set
        4#usize i20))[1]!.val =
      ((words1[0]!.val / 2 ^ 52) ||| ((words1[1]!.val * 2 ^ 12) % U64.size)) % 2 ^ 52 := by
    simp only [↓Array.getElem!_Nat_set_ne, ↓Array.getElem!_Nat_set_eq, UScalar.ofNatCore_val_eq,
      ne_eq, not_false_eq_true, one_ne_zero, OfNat.ofNat_ne_zero, Nat.succ_ne_self,
      Nat.reduceEqDiff, Nat.reduceLT, Nat.lt_add_one, Array.length, List.Vector.length_val,
      Nat.ofNat_pos, and_self,
      i8_post1, i7_post1, i4_post1, i6_post1, i2_post, i5_post,
      UScalar.val_or, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, ← Array.getElem!_Nat_eq]
  have hr2 :
      ((((((Std.Array.set ZERO 0#usize i3).set 1#usize i8).set 2#usize i13).set 3#usize i18).set
        4#usize i20))[2]!.val =
      ((words1[1]!.val / 2 ^ 40) ||| ((words1[2]!.val * 2 ^ 24) % U64.size)) % 2 ^ 52 := by
    simp only [↓Array.getElem!_Nat_set_ne, ↓Array.getElem!_Nat_set_eq, UScalar.ofNatCore_val_eq,
      ne_eq, not_false_eq_true, one_ne_zero, OfNat.ofNat_ne_zero, Nat.succ_ne_self,
      Nat.reduceEqDiff, Nat.reduceLT, Nat.lt_add_one, Array.length, List.Vector.length_val,
      Nat.ofNat_pos, and_self,
      i13_post1, i12_post1, i9_post1, i11_post1, i5_post, i10_post,
      UScalar.val_or, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, ← Array.getElem!_Nat_eq]
  have hr3 :
      ((((((Std.Array.set ZERO 0#usize i3).set 1#usize i8).set 2#usize i13).set 3#usize i18).set
        4#usize i20))[3]!.val =
      ((words1[2]!.val / 2 ^ 28) ||| ((words1[3]!.val * 2 ^ 36) % U64.size)) % 2 ^ 52 := by
    simp only [↓Array.getElem!_Nat_set_ne, ↓Array.getElem!_Nat_set_eq, UScalar.ofNatCore_val_eq,
      ne_eq, not_false_eq_true, one_ne_zero, OfNat.ofNat_ne_zero, Nat.succ_ne_self,
      Nat.reduceEqDiff, Nat.reduceLT, Nat.lt_add_one, Array.length, List.Vector.length_val,
      Nat.ofNat_pos, and_self,
      i18_post1, i17_post1, i14_post1, i16_post1, i10_post, i15_post,
      UScalar.val_or, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, ← Array.getElem!_Nat_eq]
  have hr4 :
      ((((((Std.Array.set ZERO 0#usize i3).set 1#usize i8).set 2#usize i13).set 3#usize i18).set
        4#usize i20))[4]!.val = (words1[3]!.val / 2 ^ 16) % 2 ^ 48 := by
    simp only [↓Array.getElem!_Nat_set_eq, UScalar.ofNatCore_val_eq,
      Nat.reduceLT, Nat.lt_add_one, Array.length, List.Vector.length_val,
      Nat.ofNat_pos, and_self,
      i20_post1, i19_post1, i15_post, Nat.shiftRight_eq_div_pow, ← Array.getElem!_Nat_eq]
  refine ⟨?_, ?_⟩
  · -- Value: combine bit-slicing identity with per-limb equations and the loop's word-of-bytes post
    have hslice := bit_slicing_of_words words1[0]! words1[1]! words1[2]! words1[3]!
    simp only at hslice
    -- hslice: 5-limb form = w0 + w1*2^64 + w2*2^128 + w3*2^192 (over words1[k]!.val)
    simp only [Scalar52_as_Nat, U8x32_as_Nat, word_of_bytes,
      Finset.sum_range_succ, Finset.range_zero, Finset.sum_empty, zero_add,
      pow_zero, Nat.reduceMul,
      hr0, hr1, hr2, hr3, hr4]
    -- Unfold word_of_bytes in the loop posts so they become byte sums.
    have e0 := hw0; have e1 := hw1; have e2 := hw2; have e3 := hw3
    simp only [word_of_bytes, Finset.sum_range_succ, Finset.range_zero, Finset.sum_empty,
      zero_add, Nat.reduceMul, Nat.mul_zero, Nat.zero_add, Nat.reduceAdd, pow_zero] at e0 e1 e2 e3
    -- Rewrite `words1[k]!` -> byte sum in both `hslice` and the goal so that
    -- the only remaining "atoms" are byte slots and the bit-sliced sub-expressions.
    rw [e0, e1, e2, e3] at hslice ⊢
    linarith [hslice]
  · -- Bounds: ∀ i < 5, result[i]! < 2^52
    intro idx hidx
    interval_cases idx
    · rw [hr0]; omega
    · rw [hr1]; omega
    · rw [hr2]; omega
    · rw [hr3]; omega
    · rw [hr4]; omega

end curve25519_dalek.backend.serial.u64.scalar.Scalar52
