/-
  Config: Project-specific configuration for Utils tools.

  This file centralizes all project-specific values. To adapt these tools
  for a different Aeneas-generated project, modify the values here.
-/
import Lean

open Lean

namespace Utils.Config

/-- The main module to import (contains Funs and Specs) -/
def mainModule : Name := `Curve25519Dalek

/-- The module containing function definitions -/
def funsModule : Name := `Curve25519Dalek.Funs

/-- The crate name used for relevance filtering (matches source paths) -/
def crateName : String := "curve25519-dalek"

/-!
### Suffix Filters

Functions whose name ends with any of these suffixes will be EXCLUDED.
These are internal implementation details generated by Aeneas.

TODO: The suffix-based exclusion is a workaround. The proper fix is to make
the verification checker understand that verifying a function like `foo`
should consider `foo_loop` as part of `foo`'s implementation.
-/
def excludedSuffixes : List String := [
  "_body",             -- Internal body definitions
  "_loop",             -- Loop helper functions
  "_loop._unsafe_rec",
  "_loop.mutual"
]

/-!
### Namespace Prefix Filters

Functions whose name starts with any of these prefixes will be EXCLUDED.
-/
def excludedNamespacePrefixes : List String := [
  "curve25519_dalek.core",   -- Rust core library implementations
  "curve25519_dalek.subtle", -- Subtle crate implementations
  "_private"                 -- Private/internal definitions
]

end Utils.Config
