/-
Copyright (c) 2026 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Basic
import Curve25519Dalek.Math.Edwards.Representation

/-! # Spec Theorem for `constants::EIGHT_TORSION`

Specification and proof for the constant `EIGHT_TORSION`.

This constant represents the 8-torsion subgroup E[8] of the Edwards curve,
which consists of all points P such that 8P = 0. In the case of Curve25519,
this subgroup is cyclic and is generated by a point of order 8.

The array is organized such that the i-th element is [i]P, where P is a
generator of order 8. This means:
- E[4] (the 4-torsion subgroup) consists of indices 0,2,4,6
- E[2] (the 2-torsion subgroup) consists of indices 0,4

Source: curve25519-dalek/src/backend/serial/u64/constants.rs -/

open Aeneas.Std Result Edwards
namespace curve25519_dalek.backend.serial.u64.constants

/-
natural language description:

    • EIGHT_TORSION is a constant array of 8 Edwards points representing the
      8-torsion subgroup E[8] of the Edwards curve, i.e., all points P where 8P = 0.
    • The subgroup is cyclic, generated by a point P of order 8.
    • The i-th element of the array is [i]P (i times P in the group law).
    • The element at index 0 is the identity point (0P = 0).
    • The elements at indices 0,2,4,6 form the 4-torsion subgroup E[4].
    • The elements at indices 0,4 form the 2-torsion subgroup E[2].

natural language specs:

    • All 8 elements of EIGHT_TORSION are valid Edwards points.
    • The element at index 0 is the identity point.
    • For each point P in EIGHT_TORSION, we have 8P = 0.
    • The element at index 1 has order exactly 8 (generates the entire subgroup).
    • For all i ∈ {0,...,7}, EIGHT_TORSION[i] = [i] · EIGHT_TORSION[1].
-/

/-- **Spec and proof concerning `backend.serial.u64.constants.EIGHT_TORSION`**:
    • All 8 elements are valid Edwards points
    • The first element (index 0) is the identity point
    • For each point P in the array, 8P = 0 (8-torsion property)
    • The array is cyclic: EIGHT_TORSION[i] = [i] · EIGHT_TORSION[1] for all i
-/
@[progress]
theorem EIGHT_TORSION_spec :
    (∀ i : Fin 8, EIGHT_TORSION[i.val]!.IsValid) ∧
    EIGHT_TORSION[0]!.toPoint = 0 ∧
    (∀ i : Fin 8, (8 : ℤ) • EIGHT_TORSION[i.val]!.toPoint = 0) ∧
    (∀ i : Fin 8, EIGHT_TORSION[i.val]!.toPoint = (i.val : ℤ) • EIGHT_TORSION[1]!.toPoint) := by
  constructor
  · -- All points are valid
    intro i
    unfold EIGHT_TORSION
    fin_cases i <;> decide
  constructor
  · -- First element is identity
    unfold EIGHT_TORSION
    decide
  constructor
  · -- 8-torsion property: 8P = 0 for all points
    intro i
    sorry
  · -- Cyclic property: i-th element is [i]P where P is the generator
    intro i
    sorry

end curve25519_dalek.backend.serial.u64.constants
