name: Check for Typos

# This workflow checks for common typos and spelling errors in the codebase
# using the typos tool (https://github.com/crate-ci/typos).

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  typos:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.33.1
